sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: ABAK6S9HV4LNT2jd7jF7a9XycwgMHu1vyV1kHT8cFGQaWyQChTJWlyV158h9jIx9ItFsJexn+QfPDu0Rj+GqpkNGzR1sO5y5FRvs5MoFw2N0IVw+8V8BWxek0Kas2SmbcHRkQdRDc+GoMrCDSHYK1py4kKG1rpCD6Mu2jooxx3IUMUGExKQmlDcxmvv7Te00smd6TVMskUc8kQgy4h7Z+89Uw3mune1lcqgq9QeurXtohUySCHaZQphcBDXNzF88GvD727JBXoU1DYrpbWbvlXnLwcQfG9H7AqpjR5v8PgcDrwE9xnESduuhjwhSQlYpLOADW87ybogy/EanoJk+Z/IR513a3EyZBCQOpdxyzhtsxH20KFJTk5Yh1WMvNr8CQCD3S6fPXg1x163VrA1EG9RHS5tapTli1jwnY7W1hPlSnLvEpTPRZykSkDFs38CHy3+cx3+qDLTyvd8btLwrdK6YpMS88a17HWGfgrSEZWrp648EFWpuDGfMIjaOvp1OMX9VjrseQPqkyW0TNfZlX+pjm/xFq5ZmXC8sRmH4OlvQQHHPpWXB5uVaLkcTXOnBFZapNofgMFKtezjLg8Y3XtXFOddhZnAPSaEcioOaGM5MRWOKBmqLNaTHHEcpfvzDzBhiol2roaG0cSb4c117MnKyyOR+BgCgE+B1kSoMLC8=
  - secure: AxwMUnaZbHvbsUDv/0Jyd+yQ707RRfK1+agPesX9DFzwpnyURK6B4bHeY9ejfYTm+P1jn7Bhp7yFk7yK75pgzEb6oIY4wZso5l7rjQJCvFcoE+hA/FyrolJfIx1LnFXZsk7TI39Piu+5O0RXOLD6ZmsXfwRWAar1Uf42/Dy84X/pQOcr+otcvYv290XnuSZaPluDrMyN1q9sDrxTLu5EqU+5QaL5yqH6cA/fqwMKQLNa+zvpnYWP+KmijVMeXqKmU3JFlDFPZEFhvqCQ6x0iVkzp9ImRk+y7/PcY3sUwWYXNm7VjuM+smFMyaUPeKgvOOARSZAWfJyH7fWg81zy99C/y5yxi80gzzqBOzW2RTeF+JWMkzflE7gs0ApnJR2H6qMj0Nbsq5e2va0E+FeQErvsEph+p2+scPWMNDJwBN3hiKzyCqp0WFILFszJxfcp2CJfiQYy03Hei1Z9CcSrBKuuhr9cQiB6B0xhY7QCj2PtcucwEJ8yERhNL/csUs9OJI0s6IGC+NtxJqk+WiGTwqlEjjGx0RDBshoUlMJn0P6QV7vImR8BfxumTa74ty3yeq3H+GH9gohEp1se37cTfKxOKHT57RxcemmXJD12wmLs5CiqGBFPEytU0lNYQ54BOmOz3h2txanud573UgWryLdqzcCsBk+Y/qJFjqYfj9+g=
  - secure: kvdkQO+TPqRHEfOQwhbynZIWUFdr7+FbSp9wOBTBNJeEZENCxeEsiY9EFpdEJ7m4Vzc/lWVRmBgjQsx0Xq7QYhYO68upRjnMHU/WCDwZ6SrgSQbJQ158hcJ3XKet221KI4PnAn5bgq0QY8mkB7xwZxdcKb+7IaocETJZjcG16gRMHbpDuRCTLtgld9tg/weI6VHBHvB6IhIVKHRyWN1GJ4Pq0kL8jTx471HMYbVfNunqjeVoIAxo1S26GTYvVuASmIoGMoz5/kxt5L7Fy3t3s+gmEqsGhSmpGFAZOw7PSMqE5HoKEUiTyUeXlTGcP5KbgUQcjM6KSXvSxxI9ui24MO7n6Rcx78wDLiB7EtI/M7miKP7DuMHlCQcVsXseMK/1y3InJh6s0MadnCDE57Jy08IliaKkrPtA+75WaDLKtyK+1C78OYsW+OkCQnmT8IuhXzpzRi3wcfHlxCi2TUvBDqRd/nomHx5FaClC4A93rYIx4IRNf3cTISn0djlUfuBRP95eh0seX8LIrf9Qdd+xhVvS+nncLiOjaWjnk60A+gu/5BDYXCHQzKvmTLJtj4JhlY9o1IME49fcVr5xbsuAbafs/B8cqmOXCc7GqlmD89jdW1pyUAGGDuJ3uvZHIxToKpkeT+oEwFpUkKm4GGJYB4whJk+mChPHGwCOHCLcDro=
